// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmebpqhobnlsugkaspsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtZWJwcWhvYm5sc3Vna2FzcHN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTI3MjYsImV4cCI6MjA2MDkyODcyNn0.padMrDyz6nVzM-P57nI0932tAIy7cbII7UVl4ATK4cI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);